'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/layouts/Header";
import {ReactNode} from "react";
import {Provider} from "react-redux";
import {store} from "@/app/lib/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
      <Provider store={store}>
    <html lang="en">
      <body className={inter.className}>
      <Header/>
      <main className="min-h-[96vh] h-full bg-black/20">
      {children}
      </main>
      </body>
    </html>
      </Provider>
  );
}
